strictness: veryhigh

test-warnings: true

autodetect: yes

ignore-paths:
  - build

pylint:
  disable:
    - invalid-name
    - too-many-branches
    - broad-except
    - too-many-instance-attributes
    - too-many-public-methods
    - attribute-defined-outside-init
    - too-many-return-statements
    - too-few-public-methods
    - too-many-boolean-expressions
    - too-many-locals
    - wrong-import-position
    - no-else-return
    - too-many-nested-blocks
    - too-many-statements
    - too-many-arguments
    - too-many-lines
    - simplifiable-if-statement

pep8:
  disable:
    - W503
    - E128
    - E741
    - E743
    - N802
    - N806

mccabe:
  disable:
    - MC0001

python-targets:
  - 2
