# File: .readthedocs.yaml
version: 2

# Build from the doc/directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Explicitly set the version of Python and its requirements
python:
  version: 2.7
  install:
    - requirements: doc/requirements.txt
