sudo: false
language: python

matrix:
  include:
    - python: 2.7
      env:
          TOXENV=py,codecov,coverage-report,linter,doctest,doc-html,doc-linkcheck,doc-doctest

install:
  - pip install tox
  - pip install numpy
  - pip install scipy

script:
  - tox

cache:
  - pip

notifications:
  email: true
