CMD_SOH = chr(0x01)
CMD_STX = chr(0x02)
CMD_ETX = chr(0x03)
CMD_EOT = chr(0x04)

CMD_ACK = chr(0x00)
CMD_ERR_CMD = chr(0x01)
CMD_ERR_CHKS = chr(0x02)
CMD_ERR_FORM = chr(0x03)
CMD_ERR_DATA = chr(0x04)
CMD_ERR_TOUT = chr(0x05)
CMD_ERR_ADDR = chr(0x06)
CMD_ERR_TIME = chr(0x07)
CMD_ERR_FRAME_SIZE = chr(0x08)
CMD_ERR_DATA_TYPE = chr(0x09)
CMD_ERR_PORT_TYPE = chr(0x0A)
CMD_ERR_PORT_NUMBER = chr(0x0B)
CMD_ERR_DATA_SIZE = chr(0x0C)

CMD_EXT_INQUIRY = chr(0x41)
CMD_EXT_RESET = chr(0x42)
CMD_EXT_VERSION = chr(0x43)
CMD_EXT_SAVE = chr(0x44)
CMD_EXT_RESTORE = chr(0x45)
CMD_EXT_GET_ADDR = chr(0x46)
CMD_EXT_SET_ADDR = chr(0x47)
CMD_EXT_GET_TIME = chr(0x48)
CMD_EXT_SET_TIME = chr(0x49)
CMD_EXT_GET_FRAME = chr(0x4A)
CMD_EXT_SET_FRAME = chr(0x4B)
CMD_EXT_GET_PORT = chr(0x4C)
CMD_EXT_SET_PORT = chr(0x4D)
CMD_EXT_GET_DATA = chr(0x4E)
CMD_EXT_SET_DATA = chr(0x4F)

CMD_EXT_NO_PARAMS = [
    CMD_EXT_INQUIRY,
    CMD_EXT_RESET,
    CMD_EXT_VERSION,
    CMD_EXT_SAVE,
    CMD_EXT_RESTORE,
    CMD_EXT_GET_ADDR,
    CMD_EXT_GET_TIME,
    CMD_EXT_GET_FRAME
]

CMD_EXT_WITH_PARAMS = [
    CMD_EXT_SET_ADDR,
    CMD_EXT_SET_TIME,
    CMD_EXT_SET_FRAME,
    CMD_EXT_GET_PORT,
    CMD_EXT_SET_PORT,
    CMD_EXT_GET_DATA,
    CMD_EXT_SET_DATA
]

CMD_EXT = []
CMD_EXT += CMD_EXT_NO_PARAMS + CMD_EXT_WITH_PARAMS

CMD_ABBR_INQUIRY = chr(0x61)
CMD_ABBR_RESET = chr(0x62)
CMD_ABBR_VERSION = chr(0x63)
CMD_ABBR_SAVE = chr(0x64)
CMD_ABBR_RESTORE = chr(0x65)
CMD_ABBR_GET_ADDR = chr(0x66)
CMD_ABBR_SET_ADDR = chr(0x67)
CMD_ABBR_GET_TIME = chr(0x68)
CMD_ABBR_SET_TIME = chr(0x69)
CMD_ABBR_GET_FRAME = chr(0x6A)
CMD_ABBR_SET_FRAME = chr(0x6B)
CMD_ABBR_GET_PORT = chr(0x6C)
CMD_ABBR_SET_PORT = chr(0x6D)
CMD_ABBR_GET_DATA = chr(0x6E)
CMD_ABBR_SET_DATA = chr(0x6F)

CMD_ABBR_NO_PARAMS = [
    CMD_ABBR_INQUIRY,
    CMD_ABBR_RESET,
    CMD_ABBR_VERSION,
    CMD_ABBR_SAVE,
    CMD_ABBR_RESTORE,
    CMD_ABBR_GET_ADDR,
    CMD_ABBR_GET_TIME,
    CMD_ABBR_GET_FRAME
]

CMD_ABBR_WITH_PARAMS = [
    CMD_ABBR_SET_ADDR,
    CMD_ABBR_SET_TIME,
    CMD_ABBR_SET_FRAME,
    CMD_ABBR_GET_PORT,
    CMD_ABBR_SET_PORT,
    CMD_ABBR_GET_DATA,
    CMD_ABBR_SET_DATA
]

CMD_ABBR = []
CMD_ABBR += CMD_ABBR_NO_PARAMS + CMD_ABBR_WITH_PARAMS

CMD_INQUIRY = [CMD_EXT_INQUIRY, CMD_ABBR_INQUIRY]
CMD_RESET = [CMD_EXT_RESET, CMD_ABBR_RESET]
CMD_VERSION = [CMD_EXT_VERSION, CMD_ABBR_VERSION]
CMD_SAVE = [CMD_EXT_SAVE, CMD_ABBR_SAVE]
CMD_RESTORE = [CMD_EXT_RESTORE, CMD_ABBR_RESTORE]
CMD_GET_ADDR = [CMD_EXT_GET_ADDR, CMD_ABBR_GET_ADDR]
CMD_SET_ADDR = [CMD_EXT_SET_ADDR, CMD_ABBR_SET_ADDR]
CMD_GET_TIME = [CMD_EXT_GET_TIME, CMD_ABBR_GET_TIME]
CMD_SET_TIME = [CMD_EXT_SET_TIME, CMD_ABBR_SET_TIME]
CMD_GET_FRAME = [CMD_EXT_GET_FRAME, CMD_ABBR_GET_FRAME]
CMD_SET_FRAME = [CMD_EXT_SET_FRAME, CMD_ABBR_SET_FRAME]
CMD_GET_PORT = [CMD_EXT_GET_PORT, CMD_ABBR_GET_PORT]
CMD_SET_PORT = [CMD_EXT_SET_PORT, CMD_ABBR_SET_PORT]
CMD_GET_DATA = [CMD_EXT_GET_DATA, CMD_ABBR_GET_DATA]
CMD_SET_DATA = [CMD_EXT_SET_DATA, CMD_ABBR_SET_DATA]

ACCEPTED_COMMANDS = []
ACCEPTED_COMMANDS += CMD_EXT_NO_PARAMS
ACCEPTED_COMMANDS += CMD_EXT_WITH_PARAMS
ACCEPTED_COMMANDS += CMD_ABBR_NO_PARAMS
ACCEPTED_COMMANDS += CMD_ABBR_WITH_PARAMS

SLAVE_ADDR_BROADCAST_NO_ANSWER = chr(0x00)
SLAVE_ADDR_BROADCAST_WITH_ANSWER = chr(0x7F)
SLAVE_ADDR_BROADCAST = [
    SLAVE_ADDR_BROADCAST_NO_ANSWER,
    SLAVE_ADDR_BROADCAST_WITH_ANSWER
]
SLAVE_ADDR_ACCEPTED = [chr(addr) for addr in range(0x01, 0x7F)]
SLAVE_ADDRESSES = SLAVE_ADDR_ACCEPTED + SLAVE_ADDR_BROADCAST

MASTER_ADDRESSES = [chr(addr) for addr in range(0x01, 0x7F)]
PROGRESSIVE_IDS = [chr(addr) for addr in range(0x00, 0x80)]

FRAME_SIZE_ACCEPTED = [chr(addr) for addr in range(0x01, 0x7F)]

# Index of the byte that stores the command code
SLAVE_IDX = 1
MASTER_IDX = 2
CMD_IDX = 3
ID_IDX = 4
PAR_LEN_IDX = 5
PAR_LIST_IDX = 6
CHECKSUM_IDX = -2

AD24_LEN = 8

VERSION = '\x00' * 8  # Dummy version

# Data types
DATA_TYPE_STRING = chr(0x00)
DATA_TYPE_CHAR = chr(0x01)
DATA_TYPE_STRUCT = chr(0x02)
DATA_TYPE_B01 = chr(0x03)
DATA_TYPE_B08 = chr(0x04)
DATA_TYPE_B16 = chr(0x05)
DATA_TYPE_B32 = chr(0x06)
DATA_TYPE_B64 = chr(0x07)
DATA_TYPE_U08 = chr(0x08)
DATA_TYPE_S08 = chr(0x09)
DATA_TYPE_H08 = chr(0x0A)
DATA_TYPE_O08 = chr(0x0B)
DATA_TYPE_U16 = chr(0x0C)
DATA_TYPE_S16 = chr(0x0D)
DATA_TYPE_H16 = chr(0x0E)
DATA_TYPE_O16 = chr(0x0F)
DATA_TYPE_U32 = chr(0x10)
DATA_TYPE_S32 = chr(0x11)
DATA_TYPE_H32 = chr(0x12)
DATA_TYPE_O32 = chr(0x13)
DATA_TYPE_U64 = chr(0x14)
DATA_TYPE_S64 = chr(0x15)
DATA_TYPE_H64 = chr(0x16)
DATA_TYPE_O64 = chr(0x17)
DATA_TYPE_F32 = chr(0x18)
DATA_TYPE_F64 = chr(0x19)
DATA_TYPE_PTR = chr(0x1A)

DATA_TYPE_7STRING = chr(0x20)
DATA_TYPE_7CHAR = chr(0x21)
DATA_TYPE_7STRUCT = chr(0x22)
DATA_TYPE_7B01 = chr(0x23)
DATA_TYPE_7B08 = chr(0x24)
DATA_TYPE_7B16 = chr(0x25)
DATA_TYPE_7B32 = chr(0x26)
DATA_TYPE_7B64 = chr(0x27)
DATA_TYPE_7U08 = chr(0x28)
DATA_TYPE_7S08 = chr(0x29)
DATA_TYPE_7H08 = chr(0x2A)
DATA_TYPE_7O08 = chr(0x2B)
DATA_TYPE_7U16 = chr(0x2C)
DATA_TYPE_7S16 = chr(0x2D)
DATA_TYPE_7H16 = chr(0x2E)
DATA_TYPE_7O16 = chr(0x2F)
DATA_TYPE_7U32 = chr(0x30)
DATA_TYPE_7S32 = chr(0x31)
DATA_TYPE_7H32 = chr(0x32)
DATA_TYPE_7O32 = chr(0x33)
DATA_TYPE_7U64 = chr(0x34)
DATA_TYPE_7S64 = chr(0x35)
DATA_TYPE_7H64 = chr(0x36)
DATA_TYPE_7O64 = chr(0x37)
DATA_TYPE_7F32 = chr(0x38)
DATA_TYPE_7F64 = chr(0x39)

DATA_TYPE_TIME = chr(0x40)

DATA_TYPES = [
    DATA_TYPE_STRING,
    DATA_TYPE_CHAR,
    DATA_TYPE_STRUCT,
    DATA_TYPE_B01,
    DATA_TYPE_B08,
    DATA_TYPE_B16,
    DATA_TYPE_B32,
    DATA_TYPE_B64,
    DATA_TYPE_U08,
    DATA_TYPE_S08,
    DATA_TYPE_H08,
    DATA_TYPE_O08,
    DATA_TYPE_U16,
    DATA_TYPE_S16,
    DATA_TYPE_H16,
    DATA_TYPE_O16,
    DATA_TYPE_U32,
    DATA_TYPE_S32,
    DATA_TYPE_H32,
    DATA_TYPE_O32,
    DATA_TYPE_U64,
    DATA_TYPE_S64,
    DATA_TYPE_H64,
    DATA_TYPE_O64,
    DATA_TYPE_F32,
    DATA_TYPE_F64,
    DATA_TYPE_PTR,
    DATA_TYPE_7STRING,
    DATA_TYPE_7CHAR,
    DATA_TYPE_7STRUCT,
    DATA_TYPE_7B01,
    DATA_TYPE_7B08,
    DATA_TYPE_7B16,
    DATA_TYPE_7B32,
    DATA_TYPE_7B64,
    DATA_TYPE_7U08,
    DATA_TYPE_7S08,
    DATA_TYPE_7H08,
    DATA_TYPE_7O08,
    DATA_TYPE_7U16,
    DATA_TYPE_7S16,
    DATA_TYPE_7H16,
    DATA_TYPE_7O16,
    DATA_TYPE_7U32,
    DATA_TYPE_7S32,
    DATA_TYPE_7H32,
    DATA_TYPE_7O32,
    DATA_TYPE_7U64,
    DATA_TYPE_7S64,
    DATA_TYPE_7H64,
    DATA_TYPE_7O64,
    DATA_TYPE_7F32,
    DATA_TYPE_7F64,
    DATA_TYPE_TIME
]

# Port types
PORT_TYPE_ALL = chr(0x00)
PORT_TYPE_SCI = chr(0x01)
PORT_TYPE_SPI = chr(0x02)
PORT_TYPE_IIC = chr(0x03)
PORT_TYPE_DIO = chr(0x04)
PORT_TYPE_AD = chr(0x05)
PORT_TYPE_DA = chr(0x06)
PORT_TYPE_CAN = chr(0x07)
PORT_TYPE_AD24 = chr(0x08)
PORT_TYPE_USER = chr(0x40)
PORT_TYPE_TEMP = chr(0x7A)
PORT_TYPE_PLD = chr(0x7B)
PORT_TYPE_EEP = chr(0x7C)
PORT_TYPE_RAM = chr(0x7D)
PORT_TYPE_ROM = chr(0x7E)
PORT_TYPE_CLK = chr(0x7F)

PORT_TYPES = [
    PORT_TYPE_ALL,
    PORT_TYPE_SCI,
    PORT_TYPE_SPI,
    PORT_TYPE_IIC,
    PORT_TYPE_DIO,
    PORT_TYPE_AD,
    PORT_TYPE_DA,
    PORT_TYPE_CAN,
    PORT_TYPE_AD24,
    PORT_TYPE_USER,
    PORT_TYPE_TEMP,
    PORT_TYPE_PLD,
    PORT_TYPE_EEP,
    PORT_TYPE_RAM,
    PORT_TYPE_ROM,
    PORT_TYPE_CLK
]

PORT_NUMBERS = range(0x80)
