name: Scheduled CI Python 3.9.4 and latest Python 3 Tests

on:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
        python -m pip install -r testing_requirements.txt
        python -m pip install -r doc/doc_requirements.txt
    - name: Run the unit tests
      run: |
        coverage run -p -m unittest discover -b tests
        coverage combine
        coverage xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: discos/simulators
    - name: Run the Python linter
      run: |
        prospector
    - name: Build documentation
      run: |
        sphinx-build -W -b html doc doc/_build/html
        sphinx-build -W -b doctest doc doc/_build/doctest
        sphinx-build -W -b linkcheck doc doc/_build/linkcheck
