name: Scheduled CI Python 3.6.9 and 3.9.6 Tests

on:
  schedule:
    - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6.9', '3.9.6']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: Run the unit tests
      run: |
        python -m pip install coverage
        coverage run -p -m unittest discover -b tests
        coverage combine
        coverage xml
    - name: Upload test coverage to codecov
      uses: codecov/codecov-action@v2
    - name: Run prospector
      run: |
        python -m pip install prospector
        prospector
    - name: Build documentation
      run: |
        python -m pip install sphinx sphinx_rtd_theme sphinxcontrib-bibtex
        sphinx-build -W -b html doc doc/_build/html
        sphinx-build -W -b doctest doc doc/_build/doctest
        sphinx-build -W -b linkcheck doc doc/_build/linkcheck
